name: kabaten
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.3.0
  get_it: ^7.2.0
  hive_flutter: ^1.1.0
  http: ^0.13.5
  intl: ^0.17.0
  provider: ^6.0.4
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_intl:
  main_locale: en
  enabled: true
